stages:
  - plan
  - apply
  - destroy

variables:
  WORKDIR: $CI_PROJECT_DIR/dmz
  GITLAB_TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/dmz
  PLAN: plan.tfplan
  JSON_PLAN_FILE: tfplan.json
  ENVIRONMENT_NAME: dmz

image:
  name: registry.durp.info/opentofu/opentofu:latest
  entrypoint: [""]

.tf-init:
  variables:
    TF_HTTP_ADDRESS: ${GITLAB_TF_ADDRESS}
    TF_HTTP_LOCK_ADDRESS: ${GITLAB_TF_ADDRESS}/lock
    TF_HTTP_UNLOCK_ADDRESS: ${GITLAB_TF_ADDRESS}/lock
    TF_HTTP_USERNAME: gitlab-ci-token
    TF_HTTP_PASSWORD: ${CI_JOB_TOKEN}
    TF_HTTP_LOCK_METHOD: POST
    TF_HTTP_UNLOCK_METHOD: DELETE
    TF_HTTP_RETRY_WAIT_MIN: "5"
  before_script:
    - cd $WORKDIR
    - tofu init -reconfigure

format:
  stage: .pre
  allow_failure: false
  script:
    - cd $WORKDIR
    - tofu fmt -diff -check -write=false
  rules:
    - changes:
        - "dmz/*.tf"

validate:
  stage: .pre
  allow_failure: false
  extends: .tf-init
  script:
    - tofu validate
  rules:
    - changes:
        - "dmz/*.tf"

plan-dmz-infrastructure:
  stage: plan
  environment:
    name: $ENVIRONMENT_NAME
    action: prepare
  allow_failure: false
  extends: .tf-init
  script:
    - apk add --update curl jq
    - alias convert_report="jq -r '([.resource_changes[].change.actions?]|flatten)|{\"create\":(map(select(.==\"create\"))|length),\"update\":(map(select(.==\"update\"))|length),\"delete\":(map(select(.==\"delete\"))|length)}'"
    - tofu plan -lock=false -out=$PLAN $ARGUMENTS
    - tofu show --json $PLAN | jq -r '([.resource_changes[].change.actions?]|flatten)|{"create":(map(select(.=="create"))|length),"update":(map(select(.=="update"))|length),"delete":(map(select(.=="delete"))|length)}' > $JSON_PLAN_FILE
  artifacts:
    paths:
      - $WORKDIR/$PLAN
    reports:
      terraform: $WORKDIR/$JSON_PLAN_FILE
  needs: ["validate","format"]
  rules:
    - changes:
        - "dmz/*.tf"

apply-dmz-infrastructure:
  stage: apply
  environment:
    name: $ENVIRONMENT_NAME
    on_stop: destroy-dmz-infrastructure
  allow_failure: false
  extends: .tf-init
  script:
    - tofu apply -auto-approve $PLAN
  rules:
    - changes:
        - "dmz/*.tf"
      when: manual
  needs: ["plan-dmz-infrastructure"]

destroy-dmz-infrastructure:
  stage: destroy
  environment:
    name: $ENVIRONMENT_NAME
    action: stop
  allow_failure: false
  extends: .tf-init
  script:
    - tofu destroy -auto-approve $ARGUMENTS
  rules:
    - changes:
        - "dmz/*.tf"
      when: manual
  needs: ["plan-dmz-infrastructure"]
