include:
  - project: 'developerdurp/yml'
    ref: main
    file: 
      - 'pipelines/terraform.yml'
variables:
  GITLAB_TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_COMMIT_REF_NAME}