provider "vault" {
  address         = "https://vault.infra.durp.info"
  skip_tls_verify = true

  # Authenticate as the Service Account
  auth_login {
    path = "auth/approle/login"

    parameters = {
      role_id   = var.vault_role_id
      secret_id = var.vault_secret_id
    }
  }
}

# Parse the kubeconfig generated by Talos
locals {
  kubeconfig_data = yamldecode(module.talos_infra_cluster.kubeconfig)
  cluster_context = local.kubeconfig_data.clusters[0].cluster
}

variable "vault_role_id" {
  description = "Hashi Vault AppRole ID"
  type        = string
}

variable "vault_secret_id" {
  description = "Hashi Vault AppRole Secret"
  type        = string
}

# Create a ServiceAccount for Vault to use as a Token Reviewer
resource "kubernetes_service_account_v1" "vault_reviewer" {
  metadata {
    name      = "vault-token-reviewer"
    namespace = "kube-system"
  }
}

# Grant the ServiceAccount permissions to validate other tokens
resource "kubernetes_cluster_role_binding_v1" "vault_reviewer" {
  metadata {
    name = "vault-token-reviewer-binding"
  }
  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = "system:auth-delegator"
  }
  subject {
    kind      = "ServiceAccount"
    name      = kubernetes_service_account_v1.vault_reviewer.metadata[0].name
    namespace = kubernetes_service_account_v1.vault_reviewer.metadata[0].namespace
  }
}

# In K8s 1.24+, we must manually create a Secret for the ServiceAccount token
resource "kubernetes_secret_v1" "vault_reviewer_token" {
  metadata {
    name      = "vault-token-reviewer-token"
    namespace = "kube-system"
    annotations = {
      "kubernetes.io/service-account.name" = kubernetes_service_account_v1.vault_reviewer.metadata[0].name
    }
  }
  type = "kubernetes.io/service-account-token"
}

# Configure Vault with the data extracted from the Talos cluster
# 1. Enable the Kubernetes Auth Backend
resource "vault_auth_backend" "kubernetes" {
  type = "kubernetes"
  path = "infra-cluster"
}

# 2. Configure Vault with the data extracted from the Talos cluster
resource "vault_kubernetes_auth_backend_config" "config" {
  backend                = vault_auth_backend.kubernetes.path
  kubernetes_host        = local.cluster_context.server
  kubernetes_ca_cert     = base64decode(local.cluster_context["certificate-authority-data"])
  token_reviewer_jwt     = kubernetes_secret_v1.vault_reviewer_token.data["token"]
  disable_iss_validation = true
}

# 3. Create the Role that External Secrets will use
resource "vault_kubernetes_auth_backend_role" "external_secrets" {
  backend                          = vault_auth_backend.kubernetes.path
  role_name                        = "external-secrets-role"
  bound_service_account_names      = ["external-secrets"]
  bound_service_account_namespaces = ["external-secrets"]
  token_ttl                        = 3600
  token_policies                   = ["external-secrets-policy"] # Ensure this policy exists in Vault
}

# 4. Optional: Create the policy if you haven't already
resource "vault_policy" "external_secrets" {
  name   = "external-secrets-policy"
  policy = <<EOT
path "kv/*" {
  capabilities = ["read"]
}
EOT
}

# 5. Create a Vault Policy to allow issuing certificates
resource "vault_policy" "pki_policy" {
  name   = "${local.talos.cluster_name}-pki-issuer-policy"
  policy = <<EOT
path "pki/sign/issue-homelab-certs" {
  capabilities = ["create", "update"]
}

path "pki/issue/*" {
  capabilities = ["create", "update"]
}
EOT
}

resource "random_password" "harbor_postgresql" {
  length           = 32
  special          = true
  override_special = "!@#$%&*()-_=+"
}

resource "vault_kv_secret_v2" "harbor_postgresql" {
  mount = "kv"
  name  = "harbor/postgresql"

  data_json = jsonencode({
    password = random_password.harbor_postgresql.result
  })
}

# 6. Bind the cert-manager vault-issuer ServiceAccount to the Vault Policy
resource "vault_kubernetes_auth_backend_role" "pki_issuer" {
  backend                          = vault_auth_backend.kubernetes.path
  role_name                        = "issuer"
  bound_service_account_names      = ["vault"]
  bound_service_account_namespaces = ["cert-manager"]
  token_ttl                        = 3600
  token_policies                   = [vault_policy.pki_policy.name]
}
